### ISSUE TITLE
Rewrite Transmogrify

### ISSUE THREAD

**Issue by JuniorUdale** [JuniorUdale/MoreFluff#122]
It doesn't work 100% of the time, weird slots changes sometimes linger.

**Comment by JackeeaJ** [comment]
Done... for the time being. Reset the upgrade to just return the dice, since it wouldn't work well with other dice (if I even give it to any others, that is). Also, the animation looks a bit janky for Jester? They redraw their hand, and bleh.

It's done enough; if people complain about the visuals I can always take another look.
