### ISSUE TITLE
Starsear increases Jinx and Bear Transform countdowns, and non-stackable statuses are considered valid targets for Starsear-

### ISSUE THREAD

**Issue by ncrecc** [JuniorUdale/MoreFluff#2]
For Starsear and Starsear+ just check that x isn't Jinx or Bear Transform. With Bear Transform it's simple, just ``x.type != ~beartransform~``. Jinx statuses are "jinx_" followed by a unique number so different jinxes don't stack, so you could either just check that the first five characters of x.type aren't jinx_, or if you want to futureproof this in case someone adds an ordinary status effect starting with jinx_, split x.type after the fifth character, then check that the first item isn't "jinx_" and the second item isn't an integer.

For Starsear-, make a list of acceptable statuses and filter target.status into it (excluding jinx and bear transform as described above, and when x.stacks != true), then raise a status from that list.

**Comment by ncrecc** [comment]
Also needs to exclude regen and bleed

**Comment by ncrecc** [comment]
And probably should also filter out extradamage

**Comment by JuniorUdale** [comment]
Hmmm. I had a poll on the discord about what the expected behaviour is with Jinxes, and the consensus is that it should increase the jinx countdowns. Bear Transform (and presumably survive) are also statuses, so it makes sense that it should increase them.

Nonstacking statuses and extradamage being affected is a good catch though, fixed for the next update.
