### ISSUE TITLE
Essence statuses should probably mention that they're not removed at end of turn

### ISSUE THREAD

**Issue by ncrecc** [JuniorUdale/MoreFluff#30]
Not knowing so otherwise makes the essence pack seem a bit harder than it is

**Comment by JuniorUdale** [comment]
Essences just need a major rework, methinks. They just don't *feel* interesting enough? They just feel complicated and weird and "okay, so this is like the jinx pack, but you need to play a card to activate them". Feels bad. Also, needing a single card to make the pack work doesn't sit right with me... misclicking and deleting Essence Detonator would feel awful. A few ideas to try out to make the pack feel a bit better:
* Simply make the essence statuses say "Does nothing. When invoked: do blah. Not consumed at the end of your turn" to be consistent with the current way they work.
* Maybe make them tick down by 1 each turn, and to compensate, inflict more of them? Or maybe that's just added complexity to a pack that's already a bit overloaded?
* Strip out the complexity - remove the whole "invoke" thing, and make the essences do stuff _when they're removed_, and make them remove themselves at the end of turn. (might be able to clear out some jinx jank if the timing's right). Then, Essence Detonator can be like "remove all essences, double their effects" or "deal 2 damage per essence" or something or other.
* One awful, awful idea that I might implement is making them do *slightly* different things when Warlock is active since the essences are technically statuses. Or maybe that's too weird/counterintuitive?

**Comment by ncrecc** [comment]
> * Maybe make them tick down by 1 each turn, and to compensate, inflict more of them? Or maybe that's just added complexity to a pack that's already a bit overloaded?
> * Strip out the complexity - remove the whole "invoke" thing, and make the essences do stuff _when they're removed_, and make them remove themselves at the end of turn.

Wouldn't that make this a direct retread of jinxes, then? (Except more status-oriented)

**Comment by JuniorUdale** [comment]
These are 2 seperate ideas:
* The first would be more like poison that deals no damage; e.g. you could "inflict" 6 base essence, which would deal 6 damage when invoked, but would tick down each turn. So, you'd get the most value by invoking that as early as possible.
* The second would be kind of like single-turn jinxes though, yeah, so I doubt I'll go down that route.

**Comment by JuniorUdale** [comment]
Closing this, essences are getting reworked for next patch
