### ISSUE TITLE
Do a large pass and get rid of non-functional equipment

### ISSUE THREAD

**Issue by JuniorUdale** [JuniorUdale/MoreFluff#64]
Some people play with the Randomizer mod, which lets even `excludefromrandomlists` equipment appear, so when you've used that to go "hey, this item isn't complete yet, you should never see this", Randomizer ignores that. Wouldn't want people to think this mod is unfinished or buggy or anything 🤪

**Comment by ncrecc** [comment]
If people get surprised that a mod that allows players to get *any equipment in the game* lets them get (gasp) non-functional equipment, that's more their fault :P Especially since it breaks with vanilla also - I don't see why you wouldn't be able to get the special skillcards or the player monstercards for Backstage

**Comment by JuniorUdale** [comment]
No, I mean like, there's some equipment like Sniper's Dream which is formatted to look like it does something (needs6, next equipment takes only 6s), but it... does nothing. It just feels bad that some players will be finding equipment that looks like it works but doesn't!

**Comment by ncrecc** [comment]
Right, but unexpected icky interactions (or *lack* of interactions) happen even with just vanilla and randomizer. Bow Wow Wow only works for Jester, Dice Detonator never does any damage even if you throw dice, Mechanical Arm and Forcefield (and locked cards like Ruby Weapon) don't actually depend on your rolled dice amount unless you're Robot, Spare Cycles always does 12 damage, Wheel of Fortune always affects you rather than the enemy, Uptick makes itself your skillcard, Mood Change floods your inventory, Incoming! adds Juggling Balls permanently... so unless randomizer players suddenly refuse to play without a mod that fixes all vanilla equipment, there's really no obligation for you to do anything as long as most fluff items work fine.

**Comment by JuniorUdale** [comment]
Yeah, I've come around to that way of thinking. If you're playing Randomizer, things are going to break, and that's on you!
